import 'package:flutter/material.dart';
import 'package:japurin/models/ruby.dart';

const Map<Ruby, List<Ruby>> kisuushi = {
  Ruby('1 ~ 9'): [
    Ruby('いち'),
    Ruby('に'),
    Ruby('さん'),
    Ruby('しよ・ん'),
    Ruby('ご'),
    Ruby('ろく'),
    Ruby('しち・なな'),
    Ruby('はち'),
    Ruby('きゅう'),
  ],
  Ruby('十', rubies: ['じゅう']): [
    Ruby('十', rubies: ['じゅう']),
    Ruby('二十', rubies: ['に', 'じゅう']),
    Ruby('三十', rubies: ['さん', 'じゅう']),
    Ruby('四十', rubies: ['よん', 'じゅう']),
    Ruby('五十', rubies: ['ご', 'じゅう']),
    Ruby('六十', rubies: ['ろく', 'じゅう']),
    Ruby('七十', rubies: ['なな', 'じゅう']),
    Ruby('八十', rubies: ['はち', 'じゅう']),
    Ruby('九十', rubies: ['きゅう', 'じゅう']),
  ],
  Ruby('百', rubies: ['ひゃく']): [
    Ruby('百', rubies: ['ひゃく'], color: Colors.red),
    Ruby('二百', rubies: ['に', 'ひゃく']),
    Ruby('三百', rubies: ['さん', 'びゃく'], color: Colors.blue),
    Ruby('四百', rubies: ['よん', 'ひゃく']),
    Ruby('五百', rubies: ['ご', 'ひゃく']),
    Ruby('六百', rubies: ['ろっ', 'ぴゃく'], color: Colors.blue),
    Ruby('七百', rubies: ['なな', 'ひゃく']),
    Ruby('八百', rubies: ['はっ', 'ぴゃく'], color: Colors.blue),
    Ruby('九百', rubies: ['きゅう', 'ひゃく']),
  ],
  Ruby('千', rubies: ['せん']): [
    Ruby('千', rubies: ['せん'], color: Colors.red),
    Ruby('二千', rubies: ['に', 'せん']),
    Ruby('三千', rubies: ['さん', 'ぜん'], color: Colors.blue),
    Ruby('四千', rubies: ['よん', 'せん']),
    Ruby('五千', rubies: ['ご', 'せん']),
    Ruby('六千', rubies: ['ろく', 'せん']),
    Ruby('七千', rubies: ['なな', 'せん']),
    Ruby('八千', rubies: ['はっ', 'せん']),
    Ruby('九千', rubies: ['きゅう', 'せん']),
  ],
  Ruby('万', rubies: ['まん']): [
    Ruby('一万', rubies: ['いち', 'まん']),
    Ruby('二万', rubies: ['に', 'まん']),
    Ruby('三万', rubies: ['さん', 'まん']),
    Ruby('四万', rubies: ['よん', 'まん']),
    Ruby('五万', rubies: ['ご', 'まん']),
    Ruby('六万', rubies: ['ろく', 'まん']),
    Ruby('七万', rubies: ['なな', 'まん']),
    Ruby('八万', rubies: ['はち', 'まん']),
    Ruby('九万', rubies: ['きゅう', 'まん']),
  ],
  Ruby('億', rubies: ['おく']): [
    Ruby('一億', rubies: ['いち', 'おく']),
    Ruby('二億', rubies: ['に', 'おく']),
    Ruby('三億', rubies: ['さん', 'おく']),
    Ruby('四億', rubies: ['よん', 'おく']),
    Ruby('五億', rubies: ['ご', 'おく']),
    Ruby('六億', rubies: ['ろく', 'おく']),
    Ruby('七億', rubies: ['なな', 'おく']),
    Ruby('八億', rubies: ['はち', 'おく']),
    Ruby('九億', rubies: ['きゅう', 'おく']),
  ],
  Ruby('兆', rubies: ['ちょう']): [
    Ruby('一兆', rubies: ['いち', 'ちょう']),
    Ruby('二兆', rubies: ['に', 'ちょう']),
    Ruby('三兆', rubies: ['さん', 'ちょう']),
    Ruby('四兆', rubies: ['よん', 'ちょう']),
    Ruby('五兆', rubies: ['ご', 'ちょう']),
    Ruby('六兆', rubies: ['ろく', 'ちょう']),
    Ruby('七兆', rubies: ['なな', 'ちょう']),
    Ruby('八兆', rubies: ['はち', 'ちょう']),
    Ruby('九兆', rubies: ['きゅう', 'ちょう']),
  ],
};

const Map<Ruby, List<Ruby>> josuushi = {
  Ruby('つ'): [
    Ruby('一つ', rubies: ['ひと', null]),
    Ruby('二つ', rubies: ['ふた', null]),
    Ruby('三つ', rubies: ['みっ', null]),
    Ruby('四つ', rubies: ['よっ', null]),
    Ruby('五つ', rubies: ['いつ', null]),
    Ruby('六つ', rubies: ['むっ', null]),
    Ruby('七つ', rubies: ['なな', null]),
    Ruby('八つ', rubies: ['やっ', null]),
    Ruby('九つ', rubies: ['ここの', null]),
    Ruby('十', rubies: ['とお'], color: Colors.red),
    Ruby('いくつ'),
  ],
  Ruby('個', rubies: ['こ']): [
    Ruby('一個', rubies: ['いっ', 'こ']),
    Ruby('二個', rubies: ['に', 'こ']),
    Ruby('三個', rubies: ['さん', 'こ']),
    Ruby('四個', rubies: ['よん', 'こ']),
    Ruby('五個', rubies: ['ご', 'こ']),
    Ruby('六個', rubies: ['ろっ', 'こ']),
    Ruby('七個', rubies: ['な', 'こ']),
    Ruby('八個', rubies: ['はっ', 'こ']),
    Ruby('九個', rubies: ['きゅう', 'こ']),
    Ruby('十個', rubies: ['じっ', 'こ']),
    Ruby('何個', rubies: ['なん', 'こ']),
  ],
  Ruby('枚', rubies: ['まい']): [
    Ruby('一枚', rubies: ['いち', 'まい']),
    Ruby('二枚', rubies: ['に', 'まい']),
    Ruby('三枚', rubies: ['さん', 'まい']),
    Ruby('四枚', rubies: ['よん', 'まい']),
    Ruby('五枚', rubies: ['ご', 'まい']),
    Ruby('六枚', rubies: ['ろく', 'まい']),
    Ruby('七枚', rubies: ['なな', 'まい']),
    Ruby('八枚', rubies: ['はち', 'まい']),
    Ruby('九枚', rubies: ['きゅう', 'まい']),
    Ruby('十枚', rubies: ['じゅう', 'まい']),
    Ruby('何枚', rubies: ['なん', 'まい']),
  ],
  Ruby('本', rubies: ['ほん']): [
    Ruby('一本', rubies: ['いっ', 'ぽん'], color: Colors.blue),
    Ruby('二本', rubies: ['に', 'ほん']),
    Ruby('三本', rubies: ['さん', 'ぼん'], color: Colors.blue),
    Ruby('四本', rubies: ['よん', 'ほん']),
    Ruby('五本', rubies: ['ご', 'ほん']),
    Ruby('六本', rubies: ['ろっ', 'ぽん'], color: Colors.blue),
    Ruby('七本', rubies: ['なな', 'ほん']),
    Ruby('八本', rubies: ['はっ', 'ぽん']),
    Ruby('九本', rubies: ['きゅう', 'ほん']),
    Ruby('十本', rubies: ['じっ', 'ぽん'], color: Colors.blue),
    Ruby('何本', rubies: ['なん', 'ぼん'], color: Colors.blue),
  ],
  Ruby('冊', rubies: ['さつ']): [
    Ruby('一冊', rubies: ['いっ', 'さつ']),
    Ruby('二冊', rubies: ['に', 'さつ']),
    Ruby('三冊', rubies: ['さん', 'さつ']),
    Ruby('四冊', rubies: ['よん', 'さつ']),
    Ruby('五冊', rubies: ['ご', 'さつ']),
    Ruby('六冊', rubies: ['ろく', 'さつ']),
    Ruby('七冊', rubies: ['なな', 'さつ']),
    Ruby('八冊', rubies: ['はっ', 'さつ']),
    Ruby('九冊', rubies: ['きゅう', 'さつ']),
    Ruby('十冊', rubies: ['じっ', 'さつ']),
    Ruby('何冊', rubies: ['なん', 'さつ']),
  ],
  Ruby('台', rubies: ['だい']): [
    Ruby('一台', rubies: ['いち', 'だい']),
    Ruby('二台', rubies: ['に', 'だい']),
    Ruby('三台', rubies: ['さん', 'だい']),
    Ruby('四台', rubies: ['よん', 'だい']),
    Ruby('五台', rubies: ['ご', 'だい']),
    Ruby('六台', rubies: ['ろく', 'だい']),
    Ruby('七台', rubies: ['なな', 'だい']),
    Ruby('八台', rubies: ['はち', 'だい']),
    Ruby('九台', rubies: ['きゅう', 'だい']),
    Ruby('十台', rubies: ['じゅう', 'だい']),
    Ruby('何台', rubies: ['なん', 'だい']),
  ],
  Ruby('杯', rubies: ['はい']): [
    Ruby('一杯', rubies: ['いっ', 'ぱい'], color: Colors.blue),
    Ruby('二杯', rubies: ['に', 'はい']),
    Ruby('三杯', rubies: ['さん', 'ばい'], color: Colors.blue),
    Ruby('四杯', rubies: ['よん', 'はい']),
    Ruby('五杯', rubies: ['ご', 'はい']),
    Ruby('六杯', rubies: ['ろっ', 'ぱい'], color: Colors.blue),
    Ruby('七杯', rubies: ['なな', 'はい']),
    Ruby('八杯', rubies: ['はっ', 'はい']),
    Ruby('九杯', rubies: ['きゅう', 'はい']),
    Ruby('十杯', rubies: ['じっ', 'ぱい'], color: Colors.blue),
    Ruby('何杯', rubies: ['なん', 'ばい'], color: Colors.blue),
  ],
  Ruby('足', rubies: ['そく']): [
    Ruby('一足', rubies: ['いち', 'そく']),
    Ruby('二足', rubies: ['に', 'そく']),
    Ruby('三足', rubies: ['さん', 'ぞく'], color: Colors.red),
    Ruby('四足', rubies: ['よん', 'そく']),
    Ruby('五足', rubies: ['ご', 'そく']),
    Ruby('六足', rubies: ['ろく', 'そく']),
    Ruby('七足', rubies: ['なな', 'そく']),
    Ruby('八足', rubies: ['はち', 'そく']),
    Ruby('九足', rubies: ['きゅう', 'そく']),
    Ruby('十足', rubies: ['じゅう', 'そく']),
    Ruby('何足', rubies: ['なん', 'ぞく'], color: Colors.red),
  ],
  Ruby('人', rubies: ['にん']): [
    Ruby.multi(['一人'], rubies: ['ひとり'], color: Colors.red),
    Ruby.multi(['二人'], rubies: ['ふたり'], color: Colors.red),
    Ruby('三人', rubies: ['さん', 'にん']),
    Ruby('四人', rubies: ['よ', 'にん'], color: Colors.red),
    Ruby('五人', rubies: ['ご', 'にん']),
    Ruby('六人', rubies: ['ろく', 'にん']),
    Ruby('七人', rubies: ['なな', 'にん']),
    Ruby('八人', rubies: ['はち', 'にん']),
    Ruby('九人', rubies: ['きゅう', 'にん']),
    Ruby('十人', rubies: ['じゅう', 'にん']),
    Ruby('何人', rubies: ['なん', 'にん']),
  ],
    Ruby('匹', rubies: ['ひき']): [
    Ruby('一匹', rubies: ['いっ', 'ぴき'], color: Colors.blue),
    Ruby('二匹', rubies: ['に', 'ひき']),
    Ruby('三匹', rubies: ['さん', 'びき'], color: Colors.blue),
    Ruby('四匹', rubies: ['よん', 'ひき']),
    Ruby('五匹', rubies: ['ご', 'ひき']),
    Ruby('六匹', rubies: ['ろっ', 'ぴき'], color: Colors.blue),
    Ruby('七匹', rubies: ['なな', 'ひき']),
    Ruby('八匹', rubies: ['はっ', 'ぴき'], color: Colors.blue),
    Ruby('九匹', rubies: ['きゅう', 'ひき']),
    Ruby('十匹', rubies: ['じっ', 'ぴき'], color: Colors.blue),
    Ruby('何匹', rubies: ['なん', 'びき'], color: Colors.blue),
  ],
  Ruby('頭', rubies: ['とう']): [
    Ruby('一頭', rubies: ['いっ', 'とう']),
    Ruby('二頭', rubies: ['に', 'とう']),
    Ruby('三頭', rubies: ['さん', 'とう']),
    Ruby('四頭', rubies: ['よん', 'とう']),
    Ruby('五頭', rubies: ['ご', 'とう']),
    Ruby('六頭', rubies: ['ろく', 'とう']),
    Ruby('七頭', rubies: ['なな', 'とう']),
    Ruby('八頭', rubies: ['はち', 'とう']),
    Ruby('九頭', rubies: ['きゅう', 'とう']),
    Ruby('十頭', rubies: ['じゅう', 'とう']),
    Ruby('何頭', rubies: ['なん', 'とう']),
  ],
  Ruby('羽', rubies: ['わ']): [
    Ruby('一羽', rubies: ['いち', 'わ']),
    Ruby('二羽', rubies: ['に', 'わ']),
    Ruby('三羽', rubies: ['さん', 'ば']),
    Ruby('四羽', rubies: ['よん', 'わ']),
    Ruby('五羽', rubies: ['ご', 'わ']),
    Ruby('六羽', rubies: ['ろく', 'わ']),
    Ruby('七羽', rubies: ['なな', 'わ']),
    Ruby('八羽', rubies: ['はち', 'わ']),
    Ruby('九羽', rubies: ['きゅう', 'わ']),
    Ruby('十羽', rubies: ['じゅう', 'わ']),
    Ruby('何羽', rubies: ['なん', 'わ']),
  ],
  Ruby('階', rubies: ['かい']): [
    Ruby('一階', rubies: ['いっ', 'かい'], color: Colors.blue),
    Ruby('二階', rubies: ['に', 'かい']),
    Ruby('三階', rubies: ['さん', 'がい'], color: Colors.red),
    Ruby('四階', rubies: ['よん', 'かい']),
    Ruby('五階', rubies: ['ご', 'かい']),
    Ruby('六階', rubies: ['ろっ', 'かい'], color: Colors.blue),
    Ruby('七階', rubies: ['なな', 'かい']),
    Ruby('八階', rubies: ['はっ', 'かい'], color: Colors.blue),
    Ruby('九階', rubies: ['きゅう', 'かい']),
    Ruby('十階', rubies: ['じっ', 'かい'], color: Colors.blue),
    Ruby('何階', rubies: ['なん', 'がい'], color: Colors.red),
  ],
  Ruby('回', rubies: ['かい']): [
    Ruby('一回', rubies: ['いっ', 'かい'], color: Colors.blue),
    Ruby('二回', rubies: ['に', 'かい']),
    Ruby('三回', rubies: ['さん', 'かい']),
    Ruby('四回', rubies: ['よん', 'かい']),
    Ruby('五回', rubies: ['ご', 'かい']),
    Ruby('六回', rubies: ['ろっ', 'かい'], color: Colors.blue),
    Ruby('七回', rubies: ['なな', 'かい']),
    Ruby('八回', rubies: ['はっ', 'かい'], color: Colors.blue),
    Ruby('九回', rubies: ['きゅう', 'かい']),
    Ruby('十回', rubies: ['じっ', 'かい'], color: Colors.blue),
    Ruby('何回', rubies: ['なん', 'かい']),
  ],
  Ruby('円', rubies: ['えん']): [
    Ruby('一円', rubies: ['いち', 'えん']),
    Ruby('二円', rubies: ['に', 'えん']),
    Ruby('三円', rubies: ['さん', 'えん']),
    Ruby('四円', rubies: ['よ', 'えん'], color: Colors.red),
    Ruby('五円', rubies: ['ご', 'えん']),
    Ruby('六円', rubies: ['ろく', 'えん']),
    Ruby('七円', rubies: ['なな', 'えん']),
    Ruby('八円', rubies: ['はち', 'えん']),
    Ruby('九円', rubies: ['きゅう', 'えん']),
    Ruby('十円', rubies: ['じゅう', 'えん']),
    Ruby.multi(['何', '円', '・いくら'], rubies: ['なん', 'えん', null]),
  ],
    Ruby('歳', rubies: ['さい']): [
    Ruby('一歳', rubies: ['いっ', 'さい'], color: Colors.blue),
    Ruby('二歳', rubies: ['に', 'さい']),
    Ruby('三歳', rubies: ['さん', 'さい']),
    Ruby('四歳', rubies: ['よん', 'さい']),
    Ruby('五歳', rubies: ['ご', 'さい']),
    Ruby('六歳', rubies: ['ろく', 'さい']),
    Ruby('七歳', rubies: ['なな', 'さい']),
    Ruby('八歳', rubies: ['はっ', 'さい'], color: Colors.blue),
    Ruby('九歳', rubies: ['きゅう', 'さい']),
    Ruby('十歳', rubies: ['じっ', 'さい'], color: Colors.blue),
    Ruby.multi(['何', '歳', '・いくつ'], rubies: ['なん', 'さい', null]),
  ],
  Ruby('番', rubies: ['ばん']): [
    Ruby('一番', rubies: ['いち', 'ばん']),
    Ruby('二番', rubies: ['に', 'ばん']),
    Ruby('三番', rubies: ['さん', 'ばん']),
    Ruby('四番', rubies: ['よん', 'ばん']),
    Ruby('五番', rubies: ['ご', 'ばん']),
    Ruby('六番', rubies: ['ろく', 'ばん']),
    Ruby('七番', rubies: ['なな', 'ばん']),
    Ruby('八番', rubies: ['はち', 'ばん']),
    Ruby('九番', rubies: ['きゅう', 'ばん']),
    Ruby('十番', rubies: ['じゅう', 'ばん']),
    Ruby('何番', rubies: ['なん', 'ばん']),
  ],
  Ruby('年', rubies: ['ねん']): [
    Ruby('一年', rubies: ['いち', 'ねん']),
    Ruby('二年', rubies: ['に', 'ねん']),
    Ruby('三年', rubies: ['さん', 'ねん']),
    Ruby('四年', rubies: ['よ', 'ねん'], color: Colors.red),
    Ruby('五年', rubies: ['ご', 'ねん']),
    Ruby('六年', rubies: ['ろく', 'ねん']),
    Ruby('七年', rubies: ['しち', 'ねん'], color: Colors.red),
    Ruby('八年', rubies: ['はち', 'ねん']),
    Ruby('九年', rubies: ['く', 'ねん'], color: Colors.red),
    Ruby('十年', rubies: ['じゅう', 'ねん']),
    Ruby('何年', rubies: ['なん', 'ねん']),
  ],
  Ruby('月', rubies: ['がつ']): [
    Ruby('一月', rubies: ['いち', 'がつ']),
    Ruby('二月', rubies: ['に', 'がつ']),
    Ruby('三月', rubies: ['さん', 'がつ']),
    Ruby('四月', rubies: ['し', 'がつ'], color: Colors.red),
    Ruby('五月', rubies: ['ご', 'がつ']),
    Ruby('六月', rubies: ['ろく', 'がつ']),
    Ruby('七月', rubies: ['しち', 'がつ'], color: Colors.red),
    Ruby('八月', rubies: ['はち', 'がつ']),
    Ruby('九月', rubies: ['く', 'がつ'], color: Colors.red),
    Ruby('十月', rubies: ['じゅう', 'がつ']),
    Ruby('何月', rubies: ['なん', 'がつ']),
  ],
  Ruby('か月', rubies: [null, 'げつ']): [
    Ruby('一か月', rubies: ['いっ', null, 'げつ'], color: Colors.blue),
    Ruby('二か月', rubies: ['に', null, 'げつ']),
    Ruby('三か月', rubies: ['さん', null, 'げつ']),
    Ruby('四か月', rubies: ['よん', null, 'げつ']),
    Ruby('五か月', rubies: ['ご', null, 'げつ']),
    Ruby('六か月', rubies: ['ろっ', null, 'げつ'], color: Colors.blue),
    Ruby('七か月', rubies: ['なな', null, 'げつ']),
    Ruby('八か月', rubies: ['はち', null, 'げつ'], color: Colors.red),
    Ruby('九か月', rubies: ['きゅう', null, 'げつ']),
    Ruby('十か月', rubies: ['じっ', null, 'げつ'], color: Colors.blue),
    Ruby('何か月', rubies: ['なん', null, 'げつ']),
  ],
  Ruby('週間', rubies: ['しゅう', 'かん']): [
    Ruby('一週間', rubies: ['いっ', 'しゅう', 'かん'], color: Colors.blue),
    Ruby('二週間', rubies: ['に', 'しゅう', 'かん']),
    Ruby('三週間', rubies: ['さん', 'しゅう', 'かん']),
    Ruby('四週間', rubies: ['よん', 'しゅう', 'かん']),
    Ruby('五週間', rubies: ['ご', 'しゅう', 'かん']),
    Ruby('六週間', rubies: ['ろく', 'しゅう', 'かん']),
    Ruby('七週間', rubies: ['なな', 'しゅう', 'かん']),
    Ruby('八週間', rubies: ['はっ', 'しゅう', 'かん'], color: Colors.blue),
    Ruby('九週間', rubies: ['きゅう', 'しゅう', 'かん']),
    Ruby('十週間', rubies: ['じっ', 'しゅう', 'かん'], color: Colors.blue),
    Ruby('何週間', rubies: ['なん', 'しゅう', 'かん']),
  ],
  Ruby('日', rubies: ['にち']): [
    Ruby.multi(['一日'], rubies: ['ついたち'], color: Colors.red),
    Ruby('二日', rubies: ['ふつ', 'か'], color: Colors.red),
    Ruby('三日', rubies: ['みっ', 'か']),
    Ruby('四日', rubies: ['よっ', 'か']),
    Ruby('五日', rubies: ['いつ', 'か']),
    Ruby('六日', rubies: ['むい', 'か'], color: Colors.red),
    Ruby('七日', rubies: ['なの', 'か'], color: Colors.red),
    Ruby('八日', rubies: ['よう', 'か'], color: Colors.red),
    Ruby('九日', rubies: ['ここの', 'か']),
    Ruby('十日', rubies: ['とお', 'か']),
    Ruby('何日', rubies: ['なん', 'にち']),
  ],
  Ruby('時', rubies: ['じ']): [
    Ruby('一時', rubies: ['いち', 'じ']),
    Ruby('二時', rubies: ['に', 'じ']),
    Ruby('三時', rubies: ['さん', 'じ']),
    Ruby('四時', rubies: ['よ', 'じ'], color: Colors.red),
    Ruby('五時', rubies: ['ご', 'じ']),
    Ruby('六時', rubies: ['ろく', 'じ']),
    Ruby('七時', rubies: ['しち', 'じ'], color: Colors.red),
    Ruby('八時', rubies: ['はち', 'じ']),
    Ruby('九時', rubies: ['く', 'じ'], color: Colors.red),
    Ruby('十時', rubies: ['じゅう', 'じ']),
    Ruby('何時', rubies: ['なん', 'じ']),
  ],
  Ruby('時間', rubies: ['じ', 'かん']): [
    Ruby('一時間', rubies: ['いち', 'じ', 'かん']),
    Ruby('二時間', rubies: ['に', 'じ', 'かん']),
    Ruby('三時間', rubies: ['さん', 'じ', 'かん']),
    Ruby('四時間', rubies: ['よ', 'じ', 'かん'], color: Colors.red),
    Ruby('五時間', rubies: ['ご', 'じ', 'かん']),
    Ruby('六時間', rubies: ['ろく', 'じ', 'かん']),
    Ruby('七時間', rubies: ['しち', 'じ', 'かん'], color: Colors.red),
    Ruby('八時間', rubies: ['はち', 'じ', 'かん']),
    Ruby('九時間', rubies: ['く', 'じ', 'かん'], color: Colors.red),
    Ruby('十時間', rubies: ['じゅう', 'じ', 'かん']),
    Ruby('何時間', rubies: ['なん', 'じ', 'かん']),
  ],
  Ruby('分', rubies: ['ふん']): [
    Ruby('一分', rubies: ['いっ', 'ぷん'], color: Colors.blue),
    Ruby('二分', rubies: ['に', 'ふん']),
    Ruby('三分', rubies: ['さん', 'ぷん'], color: Colors.red),
    Ruby('四分', rubies: ['よん', 'ぷん'], color: Colors.red),
    Ruby('五分', rubies: ['ご', 'ふん']),
    Ruby('六分', rubies: ['ろっ', 'ぷん'], color: Colors.blue),
    Ruby('七分', rubies: ['なな', 'ふん']),
    Ruby('八分', rubies: ['はっ', 'ぷん'], color: Colors.blue),
    Ruby('九分', rubies: ['きゅう', 'ふん']),
    Ruby('十分', rubies: ['じっ', 'ぷん'], color: Colors.blue),
    Ruby('何分', rubies: ['なん', 'ぷん'], color: Colors.red),
  ],
  Ruby('秒', rubies: ['びょう']): [
    Ruby('一秒', rubies: ['いち', 'びょう']),
    Ruby('二秒', rubies: ['に', 'びょう']),
    Ruby('三秒', rubies: ['さん', 'びょう']),
    Ruby('四秒', rubies: ['よん', 'びょう']),
    Ruby('五秒', rubies: ['ご', 'びょう']),
    Ruby('六秒', rubies: ['ろく', 'びょう']),
    Ruby('七秒', rubies: ['なな', 'びょう']),
    Ruby('八秒', rubies: ['はち', 'びょう']),
    Ruby('九秒', rubies: ['きゅう', 'びょう']),
    Ruby('十秒', rubies: ['じゅう', 'びょう']),
    Ruby('何秒', rubies: ['なん', 'びょう']),
  ],
};

const Map<String, List<String>> onbin = {
  'か': [
    '促音化', 'たまに濁音化', '促音化', '促音化', '促音化', 'たまに濁音化',
  ],
  'さ': [
    '促音化', 'たまに濁音化', '', '促音化', '促音化', 'たまに濁音化',
  ],
  'た': [
    '促音化', '', '', '促音化', '促音化', '',
  ],
  'は': [
    '促音化・半濁音化',
    '濁音化（まれに半濁音化）',
    '促音化・半濁音化',
    '促音化・半濁音化',
    '促音化・半濁音化',
    '濁音化（まれに半濁音化）',
  ],
};